package com.saurabh.E_Commerce.models.enums;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CONFIRED,
    ORDER_CANCELLED,
    ORDER_FAILED,
    ORDER_UPDATED,
    ORDER_PARTIALLY_SHIPPED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_RETURN_REQUESTED,
    ORDER_RETURN_APPROVED,
    ORDER_RETURN_REJECTED,
    ORDER_REFUNDED,


    SHIPMENT_CREATED,
    SHIPMENT_PICKED_UP,
    SHIPMENT_IN_TRANSIT,
    OUT_FOR_DELIVERY,
    DELIVERY_DELAYED,
    DELIVERED,
    DELIVERY_FAILED,

    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_PENDING,
    REFUND_INITIATED,
    REFUND_COMPLETED
}
